### ISSUE TITLE
Mongoid 3.1.7 broke my usage of mongoid-encrypted-fields

### ISSUE THREAD

**Issue by johnnyshields** [KoanHealth/mongoid-encrypted-fields#20]
Still investigating but it seems that Mongoid 3.1.7 breaks encrypted fields, specifically when I attempt to save an object, the validation fails, and then I see the encrypted chars in the input.

Rolling back to Mongoid 3.1.6 the issue goes away.

**Comment by jerryclinesmith** [comment]
I installed Mongoid 3.1.7 and all tests passed on my machine.  Have you been able to narrow down the cause?

**Comment by johnnyshields** [comment]
Have not investigated further, but the error was occurring when validating a record--it was validating based on the raw encrypted value. Could possibly due to interaction with another gem, not sure yet.

**Comment by estolfo** [comment]
Hi, is this still an issue with Mongoid 5 ?

**Comment by BiggerNoise** [comment]
@johnnyshields may be able to give a better update. 

We're no longer using this gem (or Mongo/Mongoid) and would really like to hand things off to a new maintainer. If you want to submit a P/R with tests for Mongoid 5, it would be most welcome.

**Comment by johnnyshields** [comment]
@estolfo haven't tried Mongoid 5 yet. Should be very easy to test however (when I tried w/ Mongoid 3.1.7 anything that was an encrypted field was broken)

**Comment by jerryclinesmith** [comment]
There is already a gemfile that's testing the latest Mongoid on the master branch, so I think we're OK.  I went ahead and added a gemfile to test Mongoid 5 and Rails 4 specifically.

**Comment by estolfo** [comment]
cool, thanks!
