### ISSUE TITLE
 no implicit conversion of Hash into String

### ISSUE THREAD

**Issue by curbsaleem** [KoanHealth/mongoid-encrypted-fields#23]
Hi 
i m following http://jerryclinesmith.me/blog/2013/03/29/storing-encrypted-data-in-mongodb/

when i try to update ssn 
person = Person.update_attributes(ssn: '123456789')

It throw following error
TypeError: no implicit conversion of Hash into String
from /home/test/.rvm/gems/ruby-2.1.2@nut/gems/gibberish-2.0.0/lib/gibberish/aes.rb:146:in `auth_data='

**Comment by johnnyshields** [comment]
@curbsaleem did you recently upgrade Gibberish to 2.0.0?

**Comment by curbsaleem** [comment]
yes, i m using gibberish-2.0.0.
Should i use older version ?

**Comment by johnnyshields** [comment]
Well the error is occurring in Gibberish, not in this lib. So maybe you are using code that isn't compatible with Gibberish 2.0

**Comment by johnnyshields** [comment]
OK yeah, this blog post is out of date. Either downgrade Gibberish or look at that gem for the new interface.

**Comment by curbsaleem** [comment]
yes,  working fine with 'gibberish' version  '1.4.0'

**Comment by johnnyshields** [comment]
cool. I had the same issue awhile back and I was able to upgrade after reading the new interface.
