### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by Skeyelab** [KoanHealth/mongoid-encrypted-fields#24]
This is driving me nuts.

I have a RoR app that was working on my local machine.  The app works, except when I try to save an encrypted attribute, I get an error.  This is working fine on Heroku with the exact same Gemfile and codebase.

`
class Testuser

  include Mongoid::Document
  field :email, type: String
  field :encrypted_field, type: Mongoid::EncryptedString

end
`

`[1] pry(main)> blah = Testuser.new
=> #<Testuser _id: 57046a3849c65a4bacc65561, email: nil, encrypted_field: nil>
[2] pry(main)> blah.encrypted_field = "some stuff"
TypeError: no implicit conversion of nil into String
from /Users/edahl/.rvm/gems/ruby-2.3.0@deskulator/gems/gibberish-2.0.0/lib/gibberish/aes.rb:140:in `pbkdf2_hmac'`

Any idea whats happening?

Ruby 2.3.0
Rails 4.2.6

**Comment by Skeyelab** [comment]
`source 'https://rubygems.org'
ruby "2.3.0"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'puma'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

gem 'rails_admin'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'sidekiq'
gem 'mongoid', '~> 5.1.0'
gem 'mongo'
gem 'bson_ext'
gem 'devise'

gem 'gibberish'
gem 'mongoid-encrypted-fields'

gem 'newrelic_rpm'

gem 'desk_api'
gem 'zendesk_api'

gem 'rails_12factor'
gem 'faker'
gem 'pry-rails'

gem 'sinatra', '>= 1.3.0', :require => nil

gem 'dotenv-rails', :groups => [:development, :test]

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
`

**Comment by jerryclinesmith** [comment]
It's failing inside of Gibberish - are you setting the password and salt on GibberishCipher?

**Comment by Skeyelab** [comment]
In config/application.rb I have

`    Mongoid::EncryptedFields.cipher =Gibberish::AES.new(ENV['ENCRYPTION_SALT'])`

**Comment by Skeyelab** [comment]
FYI, I've filed a similar issue here:
https://github.com/mdp/gibberish/issues/24

**Comment by jerryclinesmith** [comment]
Gibberish has changed what gets returned for AES - try using the Gibberish::AES::CBC class instead and it should work since that returns the encrypted string like we're expecting.

**Comment by Skeyelab** [comment]
similar issue:
https://gist.github.com/Skeyelab/b737b56d11a79f6fd4301f151dc5275c

**Comment by Skeyelab** [comment]
I've also been using gibberish v2 the whole time.  This app is only 2 days old. If I had to start over, I can, but I'd rather not.

**Comment by jerryclinesmith** [comment]
I just put together a simple test project, and it failed with the same error you reported, but it worked if I used the Gibberish::AES::CBC class instead of Gibberish::AES:

```
require 'gibberish/aes'
require 'mongoid'
require 'mongoid-encrypted-fields'

# Gibberish uses a unique salt for every encryption, but we need the same text to return the same ciphertext
# so Searching for encrypted field will work
class GibberishCipher

  def initialize(password, salt)
    @cipher = Gibberish::AES::CBC.new(password)
    #                       ^^^^^ must use CBC
    @salt = salt
  end

  def encrypt(data)
    @cipher.encrypt(data, salt: @salt)
  end

  def decrypt(data)
    @cipher.decrypt(data)
  end

end

class Person
  include Mongoid::Document

  field :name, type: String
  field :ssn, type: Mongoid::EncryptedString
  field :birth_date, type: Mongoid::EncryptedDate
  field :address, type: Mongoid::EncryptedHash
  field :duck_address, type: Hash
  field :ph, as: :phone_number, type: String
  field :cc, as: :credit_card, type: Mongoid::EncryptedString
end

Mongoid::EncryptedFields.cipher = GibberishCipher.new("hard password", "nacl")
Mongoid.load! "#{File.dirname(__FILE__)}/mongoid.yml"

p = Person.new
p.ssn = "123456789"

puts p.ssn
> 123456789
```

**Comment by Skeyelab** [comment]
So I need to monkeypatch the class?  Or I can just do what I'm doing:
Mongoid::EncryptedFields.cipher =Gibberish::AES::CBC.new(ENV['ENCRYPTION_SALT'])

This still doesnt explain why this was working on monday.

**Comment by Skeyelab** [comment]
Also doesn't help explain why it works on heroku as is, but not locally.  I am thinking I have some local dependency messed up but am not sure where to start.

(I appreciate the help)

**Comment by jerryclinesmith** [comment]
I would suggest you take the GibberishCipher class listed in my test code and use that.  It's just a very simple wrapper over what Gibberish provides.

I can't really explain the problem with Heroku other than checking your config there?  Make sure you have set the environment variable(s) necessary in that environment.

**Comment by Skeyelab** [comment]
This is a RoR app.  Where would you advise I put this?

**Comment by jerryclinesmith** [comment]
You can put it in app/models - not everything in that directory has to be an ActiveRecord class.  It can also just be for classes that model some behavior.  Plus, Rails will autoload it from there.

**Comment by jerryclinesmith** [comment]
I'm going to close this issue - I don't think there is a bug in this gem (or Gibberish).  If you need more help, feel free to ask.

**Comment by Skeyelab** [comment]
Thanks.  That worked.
